# Generated by Django 4.0.3 on 2022-04-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_syrfull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syrfull',
            name='video',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
